force-app/main/default/objects/Tournament__c/Tournament__c.object-meta.xml
<CustomObject>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tournament__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tournmanet type. Specifies phases that will be added to the tournament process</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cup</fullName>
            </value>
            <value>
                <fullName>Cup (with groups)</fullName>
            </value>
            <value>
                <fullName>Battle Royale</fullName>
                <isActive>false</isActive>
                <label>Battle Royale</label>
            </value>
            <value>
                <fullName>League</fullName>
                <isActive>false</isActive>
                <label>League</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TM_TournamentType.cls
public class TM_TournamentType {
    @AuraEnabled public String label;
    @AuraEnabled public String value;

    public TM_TournamentType(String label, String value) {
        this.label = label;
        this.value = value;
    }

    public TM_TournamentType(Schema.PicklistEntry picklistEntry) {
        this.label = picklistEntry.label;
        this.value = picklistEntry.value;
    }

    public static List<TM_TournamentType> getPicklistValues() {
        Schema.DescribeFieldResult typeField = Tournament__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = typeField.getPicklistValues();

        List<TM_TournamentType> result = new List<TM_TournamentType>();
        for (Schema.PicklistEntry picklistValue : picklistValues) {
            result.add(new TM_TournamentType(picklistValue));
        }

        return result;
    }
}